### ISSUE TITLE
【建议】所说的 可以安装桌面，docker全部可以，docker还共享内核，几乎没有性能损耗

### ISSUE THREAD

**Issue by zhaojinzhou** [shenuiuin/LXD_GPU_SERVER#10]
我用docker。

**Comment by shenuiuin** [comment]
> 我用docker。

我也只是提供了一个解决方案，lxd也是共享内核的，损耗也很小，至于docker我只是用做应用容器，lxd作为系统容器更加接近于系统级的开发环境
