### ISSUE TITLE
你好，按你的步骤来，在端口转发处有点问题

### ISSUE THREAD

**Issue by tdf1995** [shenuiuin/LXD_GPU_SERVER#4]
显示connection refused，请问有解决办法吗

**Comment by shenuiuin** [comment]
> 显示connection refused，请问有解决办法吗

具体表现为什么呢，是连接ssh的时候吗？如果是的话，端口转发应该已经成功了。是容器的SSH问题，那就直接搜ssh拒绝连接，然后编辑你的容器中的ssh服务，

**Comment by tdf1995** [comment]
现在是这么个情况，在宿主机上用ssh容器的IP可以进入，但是连宿主机的ip的转发端口号会要求输入密码，输入设置的密码也不对，提示permission denied，请问要怎么解决？

**Comment by shenuiuin** [comment]
> 现在是这么个情况，在宿主机上用ssh容器的IP可以进入，但是连宿主机的ip的转发端口号会要求输入密码，输入设置的密码也不对，提示permission denied，请问要怎么解决？

你在宿主机上用ssh容器的IP不需要密码吗？还有连接的用户需要注意，是root还是普通用户，最后在教程下面有端口转发表的管理，你看一下有没有重复或者冲突的规则。或者你可以加我QQ。我看一下具体的情况

**Comment by tdf1995** [comment]
能QQ交流是最好的了，我的QQ491744814

**Comment by Mokyyds** [comment]
> > 现在是这么个情况，在宿主机上用ssh容器的IP可以进入，但是连宿主机的ip的转发端口号会要求输入密码，输入设置的密码也不对，提示permission denied，请问要怎么解决？
> 
> 你在宿主机上用ssh容器的IP不需要密码吗？还有连接的用户需要注意，是root还是普通用户，最后在教程下面有端口转发表的管理，你看一下有没有重复或者冲突的规则。或者你可以加我QQ。我看一下具体的情况

请问大佬，这种解决方案是实验室内一个用户分配一个宿主机的端口，然后再把这个端口转发到容器的22端口上嘛？

**Comment by shenuiuin** [comment]
> > > 现在是这么个情况，在宿主机上用ssh容器的IP可以进入，但是连宿主机的ip的转发端口号会要求输入密码，输入设置的密码也不对，提示permission denied，请问要怎么解决？
> > 
> > 
> > 你在宿主机上用ssh容器的IP不需要密码吗？还有连接的用户需要注意，是root还是普通用户，最后在教程下面有端口转发表的管理，你看一下有没有重复或者冲突的规则。或者你可以加我QQ。我看一下具体的情况
> 
> 请问大佬，这种解决方案是实验室内一个用户分配一个宿主机的端口，然后再把这个端口转发到容器的22端口上嘛？

对
